--USE DATABASE SNOWFLAKE_SAMPLE_DATA

--USE SCHEMA WEATHER

CREATE OR REPLACE TRANSIENT TABLE SUPPLIER_BLOCK_ALG
AS
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.SUPPLIER sample system (3) seed (82);

CREATE OR REPLACE TRANSIENT TABLE SUPPLIER_ROW_ALG
AS
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.SUPPLIER sample row (3) seed (82);

CREATE OR REPLACE TRANSIENT TABLE SUPPLIER_CLONE CLONE SUPPLIER

CREATE OR REPLACE TRANSIENT TABLE SUPPLIER as select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.SUPPLIER